# values.yaml
namespace: helm
backend:
  host: mysql-service
  dbname: projectdb
  username: root
  allowed-origin: http://myapp.com
  replicas: 2
  image: elmazidi/backend-app:4.0.0
  domain: myapp-api.com

frontend:
  replicas: 2
  image: elmazidi/frontend-app:5.0.0
  domain: myapp.com

mysql:
  password: cGFzc3dvcmQ=
  replicas: 2
  image: mysql:8.2.0

